[tool.poetry]
name = "gurobi"
version = "0.1.0"
description = ""
authors = ["Guilherme Prado <guizmk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gurobipy = "^11.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
